INSERT INTO comments (pin_id, owner_id, description)
VALUES
  (1, 14, 'Wow! Makes Javascript so easy'),
  (1, 8, 'I prefer python'),
  (2, 7, 'This helps me so much!!'),
  (2, 18, 'I already knew this, waste of time!'),
  (3, 5, 'Thanks! this will help so much'),
  (3, 12, 'THESE TOOLS ARE CRAZY!'),
  (4, 10, 'I waste so much of my time... I need this to work'),
  (4, 16, 'Should be studying but im here instead.'),
  (5, 20, 'React is really hard!'),
  (5, 3, 'React is easy why do people need this'),
  (6, 19, 'This really brought me to the next level of React!'),
  (6, 4, 'I needed this so much!'),
  (7, 2, 'Less is always more I say.'),
  (7, 13, 'Maybe this is a bit too simple'),
  (8, 17, 'Uh its Colour...'),
  (8, 6, 'Wow so many pretty colors!'),
  (9, 15, 'This is basics? I dont understand.'),
  (9, 11, 'This is a little too easy even for basics!'),
  (10, 9, 'Thanks! Im sneaking this cheat sheet into my next test!'),
  (10, 1, 'Could of used more info..'),
  (11, 12, 'wow css is so fun!'),
  (11, 15, 'I dont get it...'),
  (12, 18, 'Forget this... Play flexzombies instead'),
  (12, 3, 'I think im starting to get it!'),
  (13, 6, 'Thats it im getting off the internet and getting some work in! I CAN DO IT'),
  (13, 17, 'These are great quotes thanks!'),
  (14, 10, 'You forgot HELLO WORLD!'),
  (14, 1, 'I dont know any of these people...'),
  (15, 9, 'We are all just seeds in the cosmic database of life.'),
  (15, 20, 'Wow databases are fun!'),
  (16, 2, 'Databases are so hard! Whyyyyy'),
  (16, 16, 'Could be better'),
  (17, 5, 'Not enough tips!'),
  (17, 19, 'Im so shy... Do I really need to talk to other people to network?'),
  (18, 11, 'I use my LinkedIn like its facebook!'),
  (18, 13, 'I never understood LinkedIn... UNTIL TODAY'),
  (19, 4, 'Python is so simple..'),
  (19, 7, '55? Really?'),
  (20, 8, 'Wow this is lazy posting.'),
  (20, 14, 'My dad owns Python and im tellin him you said this!'),
  (21, 12, 'Thank you I needed this.'),
  (21, 16, 'We all need to be open about mental health!'),
  (22, 18, 'I feel like a imposter all the time!'),
  (22, 1, 'Thank you for this.'),
  (23, 3, 'A wizard? What spells will I learn from this?'),
  (23, 19, 'Thanks so much! this is so much more clear now!'),
  (24, 5, 'This is a great cheatsheet! This is going right on my samsung smart fridge'),
  (24, 6, 'Maybe include a bit more on the sheet next time?'),
  (25, 7, 'I always forget my git commands!'),
  (25, 11, 'Is it pronounced like git or jit?'),
  (26, 13, 'I dont need version control! I can just be careful.'),
  (26, 15, 'This is great thanks!'),
  (27, 2, 'These are some great tutorials!'),
  (27, 10, 'I dont like this'),
  (28, 17, 'WOW these tutorials are crazy!'),
  (28, 20, 'So So.'),
  (29, 9, 'This always puts me in a good study zone.'),
  (29, 14, 'LOFI YAAAA'),
  (30, 4, 'some of the best study songs!'),
  (30, 8, 'I cant focus without classical.'),
  (31, 6, 'why isnt BillyBob Tech on this list?'),
  (31, 3, 'Matt the tech man should of been 1st..'),
  (32, 15, 'you use a usb for one thing and thats it..'),
  (32, 1, 'WOW! usbs can do that?'),
  (33, 11, 'I wish this was close to me! I would go!'),
  (33, 7, 'This is right next door to me! Im coming for sure!'),
  (34, 16, 'This looked really fun!'),
  (34, 2, 'These highlights are great.');
  