-- pins table seeds, two pins per category
INSERT INTO pins (url, title, description, image_id, owner_id, category_id)
VALUES
  ('https://www.example.com/pin1', 'Javascript fundamentals', 'The 7 Fundamentals Of Javascript.', 1, 1, 1),
  ('https://www.example.com/pin2', 'Productivity Tools', 'Boost your efficiency with these amazing tools.', 2, 2, 2),
  ('https://www.example.com/pin3-2', 'Learning React: The Main Concepts', 'Mastering these key React concepts will help you very quickly.', 3, 20, 3),
  ('https://www.example.com/pin4', 'Minimalist Design', 'Simplicity is the ultimate sophistication.', 4, 4, 4),
  ('https://www.example.com/pin5', 'HTML Basics', 'Get started with the fundamentals of HTML.', 5, 5, 5),
  ('https://www.example.com/pin17', 'Programming welcome week', 'Welcome Week Activities sponsored by Student Programming Board.', 17, 17, 17),
  ('https://www.example.com/pin6', 'CSS Styling', 'Create stunning designs with CSS.', 6, 6, 6),
  ('https://www.example.com/pin7', 'Inspirational Quotes', 'Fuel your motivation with these powerful quotes.', 7, 7, 7),
  ('https://www.example.com/pin8', 'Database Essentials', 'Learn about databases and their importance.', 8, 8, 8),
  ('https://www.example.com/pin9', 'Networking Tips', 'Build your professional network with these strategies.', 9, 9, 9),
  ('https://www.example.com/pin3', 'React Masterclass', 'Learn everything about React in this comprehensive course.', 3, 3, 3),
  ('https://www.example.com/pin10-2', 'Is Python better than Javascript?', 'No.', 10, 7, 10),
  ('https://www.example.com/pin4-2', 'Color psychology and its best practices', 'Color has an essential role in the visual experience. It is a powerful information medium for human cognitive ability.', 4, 1, 4),
  ('https://www.example.com/pin11', 'Mental Health Matters', 'Prioritize your mental well-being with these insights.', 11, 11, 11),
  ('https://www.example.com/pin12', 'Ruby wizard', 'Explore lesser-known Ruby tricks.', 12, 12, 12),
  ('https://www.example.com/pin13-2', 'Version Control with Git', 'Learn the art of version control using Git.', 13, 10, 13),
  ('https://www.example.com/pin2-2', 'Time Management', 'Daily Time Management of Extremely Productive People.', 2, 19, 2),
  ('https://www.example.com/pin14-2', 'Creative Tutorials Compilation', 'A collection of creative tutorials for various skills.', 14, 11, 14),
  ('https://www.example.com/pin15-2', 'Calming classical music', 'Enhance your focus with classical study music.', 15, 12, 15),
  ('https://www.example.com/pin16', 'Top 10 Tech YouTube Channels', 'Best Youtube Tech stars!.', 16, 16, 16),
  ('https://www.example.com/pin8-2', 'Effective Database Management', 'Efficiently manage databases for your projects.', 8, 5, 8),
  ('https://www.example.com/pin5-2', 'HTML5 Cheat Sheet', 'Master html like a pro with this cheatsheet!', 5, 2, 5),
  ('https://www.example.com/pin12-2', 'Ruby cheatsheet', 'Master Ruby with this cheatsheet!', 12, 9, 12),
  ('https://www.example.com/pin16-2', '10 Practical Uses for a USB', 'You have used USB sticks to transport files between computers and back up files, but there is much more you can do!', 16, 13, 16),
  ('https://www.example.com/pin9-2', 'LinkedIn Profile Checklist', 'How do you optimize your LinkedIn profile? . Use this quick checklist.', 9, 6, 9),
  ('https://www.example.com/pin6-2', 'CSS Flexbox Tutorial', 'This is a complete flexbox tutorial with a cheatsheet.', 6, 3, 6),
  ('https://www.example.com/pin15', 'Lofi Playlist', 'This relaxing study music is perfect for stress relief and relaxing whilst studying.', 15, 15, 15),
  ('https://www.example.com/pin7-2', 'Inspirational Programming Quotes', 'Stay motivated with these inspirational programming quotes.', 7, 4, 7),
  ('https://www.example.com/pin1-2', 'Advanced JavaScript Techniques', 'Explore advanced JavaScript concepts and techniques.', 1, 18, 1),
  ('https://www.example.com/pin13', 'Git Essentials', 'Master the basics of version control with Git.', 13, 13, 13),
  ('https://www.example.com/pin11-2', 'Types of Imposter Syndrome', 'Do you suffer from imposter syndrome at work or life? Find your type and discover the ways you can stop being the "prisoner".', 11, 8, 11),
  ('https://www.example.com/pin10', '55 Python Project Ideas', 'Check out this list of Python project ideas for beginners.', 10, 10, 10),
  ('https://www.example.com/pin17-2', 'Programming Event Highlights', 'Highlights from recent programming-related events.', 17, 14, 17),
  ('https://www.example.com/pin14', 'Tutorial Compilation', 'A curated list of tutorials for various topics.', 14, 14, 14);
